# Generated by Django 5.2.9 on 2025-12-18 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_proyecto_usuario_id_delete_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='modulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='url',
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('modulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('imagen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imagen')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
