# Generated by Django 5.2.10 on 2026-01-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagen_id_alter_mesa_id_alter_modulo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='imagen_id',
        ),
        migrations.AddField(
            model_name='mesa',
            name='imagen_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_asignadas', to='api.imagen'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
