# Generated by Django 5.2.10 on 2026-01-19 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_queues_and_phase_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'api_planta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RenameIndex(
            model_name='imagen',
            new_name='api_imagen_modulo__04db4f_idx',
            old_name='api_imagen_modulo__idx',
        ),
        migrations.RenameIndex(
            model_name='imagen',
            new_name='api_imagen_modulo__d9ad6f_idx',
            old_name='api_imagen_modulo__fase_idx',
        ),
        migrations.RenameIndex(
            model_name='imagen',
            new_name='api_imagen_modulo__558a48_idx',
            old_name='api_imagen_modulo__fase_orden_idx',
        ),
        migrations.RenameIndex(
            model_name='mesaqueueitem',
            new_name='api_mesa_qu_mesa_id_2d25d0_idx',
            old_name='api_mesa_qi_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='mesaqueueitem',
            new_name='api_mesa_qu_mesa_id_a0eae5_idx',
            old_name='api_mesa_qi_status_idx',
        ),
        migrations.RenameIndex(
            model_name='mesaqueueitem',
            new_name='api_mesa_qu_modulo__915fdb_idx',
            old_name='api_mesa_qi_mod_fase_idx',
        ),
        migrations.RenameIndex(
            model_name='moduloqueueitem',
            new_name='api_modulo__queue_i_2a2d86_idx',
            old_name='api_mqi_queue_pos_idx',
        ),
        migrations.RenameIndex(
            model_name='moduloqueueitem',
            new_name='api_modulo__modulo__a4aaf6_idx',
            old_name='api_mqi_modulo_idx',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.modulo'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='api.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='imagen',
            table='api_imagen',
        ),
        migrations.AlterModelTable(
            name='mesa',
            table='api_mesa',
        ),
        migrations.AlterModelTable(
            name='modulo',
            table='api_modulo',
        ),
        migrations.AlterModelTable(
            name='proyecto',
            table='api_proyecto',
        ),
        migrations.AddField(
            model_name='planta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='api.proyecto'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='api.planta'),
        ),
        migrations.AddConstraint(
            model_name='planta',
            constraint=models.UniqueConstraint(fields=('proyecto', 'nombre'), name='unique_planta_nombre_per_proyecto'),
        ),
    ]
