# Generated by Django 5.2.10 on 2026-01-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_planta_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_organizacion',
            },
        ),
        migrations.AddField(
            model_name='imagen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='imagen',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=20)),
                ('action_type', models.CharField(choices=[('ASSIGN_TO_MESA', 'Assign to Mesa'), ('UNASSIGN', 'Unassign'), ('REORDER_QUEUE', 'Reorder Queue'), ('MARK_DONE', 'Mark Done'), ('PUBLISH_IMAGE', 'Publish Image'), ('ARCHIVE_IMAGE', 'Archive Image'), ('UPDATE_CALIBRATION', 'Update Calibration'), ('BLACKOUT_TOGGLE', 'Blackout Toggle')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organizacion')),
            ],
            options={
                'db_table': 'api_activity_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='api.organizacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='api.organizacion'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INAK_ADMIN', 'INAK Admin'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_profile',
            },
        ),
    ]
