# Generated by Django 5.2.10 on 2026-01-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_organizacion_imagen_archivo_imagen_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mesaqueueitem',
            name='api_mesa_qu_mesa_id_a0eae5_idx',
        ),
    ]
