# Generated by Django 5.2.10 on 2026-01-20 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mesaqueueitem_api_mesa_qu_mesa_id_a0eae5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='actor_user',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='mesa',
            name='calibration_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='device_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='mapper_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pairing_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pairing_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mesaqueueitem',
            index=models.Index(fields=['mesa', 'status'], name='api_mesa_qu_mesa_id_a0eae5_idx'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Organizacion',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
