# Generated by Django 5.2.10 on 2026-01-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_activitylog_actor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pairing_code', models.CharField(max_length=10, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('device_token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mesa')),
            ],
            options={
                'db_table': 'api_pairing_session',
            },
        ),
    ]
