# Generated by Django 5.2.10 on 2026-01-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_proyecto_usuario_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaqueueitem',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa_queue_items', to='api.imagen'),
        ),
    ]
