# Generated by Django 5.2.10 on 2026-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_mesaqueueitem_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_texto_plano',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
