# Generated by Django 5.2.10 on 2026-01-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_password_texto_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='fichero_corte',
            field=models.FileField(blank=True, null=True, upload_to='cortes/'),
        ),
        migrations.AddField(
            model_name='planta',
            name='plano_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planos/'),
        ),
    ]
