# Generated by Django 5.2.10 on 2026-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_planta_fichero_corte_planta_plano_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='current_image_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
