# Generated by Django 5.2.10 on 2026-01-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_mesa_current_image_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='current_image_index',
            field=models.IntegerField(default=0),
        ),
    ]
