# Generated by Django 5.2.10 on 2026-02-10 18:08

from django.db import migrations



def remove_duplicates(apps, schema_editor):
    MesaQueueItem = apps.get_model('api', 'MesaQueueItem')
    # Use direct SQL or ORM to find duplicates
    from django.db.models import Count
    
    # 1. Find duplicates
    duplicates = MesaQueueItem.objects.values('modulo', 'fase').annotate(count=Count('id')).filter(count__gt=1)
    
    for dup in duplicates:
        modulo_id = dup['modulo']
        fase = dup['fase']
        
        # Get all items for this combo
        items = MesaQueueItem.objects.filter(modulo_id=modulo_id, fase=fase).order_by('-id')
        
        # Determine which one to keep
        # Logic: Keep MOSTRANDO if exists, else keep latest
        mostrando_items = items.filter(status='MOSTRANDO')
        
        if mostrando_items.exists():
            keeper = mostrando_items.first()
        else:
            keeper = items.first() # Latest
            
        # Delete others
        for item in items:
            if item.id != keeper.id:
                print(f"Deleting duplicate Modulo {modulo_id} ({fase}) Item {item.id}")
                item.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_mesa_current_image_index'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterUniqueTogether(
            name='mesaqueueitem',
            unique_together={('modulo', 'fase')},
        ),
    ]
