# Generated by Django 5.2.10 on 2026-02-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mesaqueueitem_active_assignment_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='codigos_color',
            field=models.JSONField(blank=True, default=list, help_text='Array de codigos de color, ej: ["pink", "green", "blue", "yellow"]'),
        ),
        migrations.CreateModel(
            name='FotoFabricacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fase', models.CharField(choices=[('INFERIOR', 'Inferior'), ('SUPERIOR', 'Superior')], max_length=20)),
                ('paso', models.PositiveIntegerField(help_text='Indice de imagen (0-based) en el que se capturo la foto')),
                ('url', models.CharField(help_text='Ruta URL relativa al archivo de foto almacenado', max_length=500)),
                ('capturada_at', models.DateTimeField(auto_now_add=True)),
                ('filename_original', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamano del archivo en bytes', null=True)),
                ('imagen_referencia', models.ForeignKey(blank=True, help_text='Imagen de plano que se estaba proyectando al capturar esta foto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_evidencia', to='api.imagen')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_capturadas', to='api.mesa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_fabricacion', to='api.modulo')),
            ],
            options={
                'db_table': 'api_foto_fabricacion',
                'ordering': ['-capturada_at'],
                'indexes': [models.Index(fields=['modulo', 'fase'], name='api_foto_fa_modulo__9fbe08_idx'), models.Index(fields=['modulo', 'fase', 'paso'], name='api_foto_fa_modulo__3f77db_idx'), models.Index(fields=['mesa'], name='api_foto_fa_mesa_id_554875_idx')],
            },
        ),
    ]
