# Generated by Django 5.2.10 on 2026-04-14 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_modulo_codigos_color_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='rol',
            field=models.CharField(choices=[('LEGACY', 'Mesa Legacy'), ('INFERIOR_1', 'Inferior 1 + Montaje'), ('INFERIOR_2', 'Inferior 2 + Montaje'), ('SUPERIORES', 'Superiores')], default='LEGACY', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='bastidor_longitud_cm',
            field=models.DecimalField(decimal_places=2, default=114, help_text='Longitud util del bastidor para calcular capacidad por espesor.', max_digits=6),
        ),
        migrations.CreateModel(
            name='DetalleModuloFase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fase', models.CharField(choices=[('INFERIOR', 'Inferior'), ('SUPERIOR', 'Superior')], max_length=20)),
                ('espesor_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_malla_inicial_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('peso_malla_final_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('desperdicio_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cantidad_cortes', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_refuerzos', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_refuerzos_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cantidad_zunchos', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_zunchos_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cantidad_separadores', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_separadores_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cantidad_punzos', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_punzos_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dificultad_fabricacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_fase', to='api.modulo')),
            ],
            options={
                'db_table': 'api_detalle_modulo_fase',
                'ordering': ['modulo', 'fase'],
            },
        ),
        migrations.CreateModel(
            name='GrupoMesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_mesas_activos', to='api.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_mesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_grupo_mesas',
                'ordering': ['usuario__username', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='api.grupomesas'),
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(condition=models.Q(('grupo__isnull', False), models.Q(('rol', 'LEGACY'), _negated=True)), fields=('grupo', 'rol'), name='unique_rol_por_grupo_mesas'),
        ),
        migrations.AddIndex(
            model_name='detallemodulofase',
            index=models.Index(fields=['modulo', 'fase'], name='api_detalle_modulo__4081de_idx'),
        ),
        migrations.AddIndex(
            model_name='detallemodulofase',
            index=models.Index(fields=['fase'], name='api_detalle_fase_099dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='detallemodulofase',
            constraint=models.UniqueConstraint(fields=('modulo', 'fase'), name='unique_detalle_modulo_por_fase'),
        ),
        migrations.AddConstraint(
            model_name='detallemodulofase',
            constraint=models.CheckConstraint(condition=models.Q(('fase__in', ['INFERIOR', 'SUPERIOR'])), name='check_detalle_modulo_fase_valid'),
        ),
        migrations.AddConstraint(
            model_name='grupomesas',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='unique_grupo_mesas_nombre_por_usuario'),
        ),
    ]
