# Generated by Django 5.2.10 on 2026-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mesa_rol_proyecto_bastidor_longitud_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho util del modulo para agrupacion en bastidor.', max_digits=6, null=True),
        ),
    ]
