# Generated by Django 5.2.10 on 2026-04-14 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_modulo_ancho_cm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaqueueitem',
            name='plan_group_index',
            field=models.PositiveIntegerField(blank=True, help_text='Indice de grupo de bastidor dentro de la planificacion automatica.', null=True),
        ),
        migrations.AddIndex(
            model_name='mesaqueueitem',
            index=models.Index(fields=['mesa', 'plan_group_index'], name='api_mesa_qu_mesa_id_79550d_idx'),
        ),
    ]
