# Generated by Django 5.2.10 on 2026-05-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_mesa_check_overlay'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_material', models.CharField(max_length=80)),
                ('informado', models.BooleanField(default=False)),
                ('origen', models.CharField(blank=True, choices=[('PROYECTO', 'Proyecto'), ('GENERAL', 'General')], max_length=20, null=True)),
                ('fecha_marcado', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_informados', to='api.proyecto')),
            ],
            options={
                'db_table': 'api_material_informado',
                'indexes': [models.Index(fields=['proyecto', 'informado'], name='api_materia_proyect_2c4b91_idx'), models.Index(fields=['clave_material'], name='api_materia_clave_m_5b0ca7_idx')],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'clave_material'), name='unique_material_informado_proyecto_clave')],
            },
        ),
        migrations.CreateModel(
            name='MaterialPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REFUERZO', 'Refuerzo'), ('BARRA_SOLAPE', 'Barra de solape de zuncho'), ('ZUNCHO', 'Zuncho'), ('SEPARADOR', 'Separador'), ('PUNZO', 'Punzonamiento')], max_length=20)),
                ('capa', models.CharField(choices=[('INFERIOR', 'Inferior'), ('SUPERIOR', 'Superior')], max_length=20)),
                ('subtipo', models.CharField(max_length=40)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=10)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='api.modulo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='api.proyecto')),
            ],
            options={
                'db_table': 'api_material_pieza',
                'indexes': [models.Index(fields=['proyecto', 'tipo', 'subtipo'], name='api_materia_proyect_534925_idx'), models.Index(fields=['modulo', 'capa'], name='api_materia_modulo__e8a6f7_idx')],
            },
        ),
    ]
