# Generated by Django 5.2.10 on 2026-06-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_contactos_y_direcciones(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model('api', 'UserProfile')
    FerrallaContacto = apps.get_model('api', 'FerrallaContacto')
    FerrallaDireccion = apps.get_model('api', 'FerrallaDireccion')

    for profile in UserProfile.objects.all():
        try:
            user = User.objects.get(pk=profile.user_id)
        except User.DoesNotExist:
            continue

        contacto_tiene_datos = any([
            profile.coordinador,
            profile.telefono,
            user.email,
        ])
        if contacto_tiene_datos and not FerrallaContacto.objects.filter(user_id=user.id).exists():
            FerrallaContacto.objects.create(
                user_id=user.id,
                nombre=profile.coordinador or '',
                cargo='',
                telefono=profile.telefono or '',
                email=user.email or '',
                orden=0,
            )

        if profile.direccion and not FerrallaDireccion.objects.filter(user_id=user.id).exists():
            FerrallaDireccion.objects.create(
                user_id=user.id,
                nombre='Principal',
                direccion=profile.direccion,
                orden=0,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_modulo_orden_intra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FerrallaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_ferralla_contacto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FerrallaDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('direccion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_ferralla_direccion',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.RunPython(migrate_legacy_contactos_y_direcciones, noop_reverse),
    ]
