# Generated by Django 5.2.10 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_ferrallacontacto_ferralladireccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='datos_tecnicos_actualizados_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fichero_datos_tecnicos',
            field=models.FileField(
                blank=True,
                help_text='Ultima fuente tecnica valida importada para el proyecto.',
                null=True,
                upload_to='datos_tecnicos/',
            ),
        ),
    ]
