# Generated by Django 5.2.10 on 2026-08-11 11:51

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_proyecto_fichero_datos_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capture_config_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='capture_config_applied_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesa',
            name='capture_config_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mesa',
            name='capture_config_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='capture_config_revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mesa',
            name='image_rotation',
            field=models.PositiveSmallIntegerField(default=180, help_text='Rotacion de las capturas de esta mesa: 0, 90, 180 o 270 grados.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='capture_active_days',
            field=models.JSONField(default=api.models.default_capture_active_days),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='capture_end_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='capture_interval_seconds',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='capture_start_time',
            field=models.TimeField(default=datetime.time(6, 50)),
        ),
    ]
