# Generated by Django 5.2.10 on 2026-08-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomesas',
            name='estrategia_cola_superior',
            field=models.CharField(choices=[('PLANIFICADA', 'Alternancia planificada'), ('ADAPTATIVA', 'Adaptar al avance real')], default='PLANIFICADA', help_text='PLANIFICADA mantiene la alternancia teorica. ADAPTATIVA prioriza los superiores ya requeridos por las mesas inferiores.', max_length=20),
        ),
        migrations.AddField(
            model_name='modulo',
            name='superior_needed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Momento desde el que produccion inferior necesita esta fase superior. Permite ordenar la mesa SUP por demanda real.', null=True),
        ),
    ]
