# Generated by Django 5.2.10 on 2026-09-04 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_phase_dates(apps, schema_editor):
    Modulo = apps.get_model('api', 'Modulo')
    QueueItem = apps.get_model('api', 'MesaQueueItem')
    for phase, prefix in [('INFERIOR', 'inferior'), ('SUPERIOR', 'superior')]:
        latest = QueueItem.objects.filter(
            modulo_id=models.OuterRef('pk'), fase=phase, status='HECHO', done_at__isnull=False,
        ).order_by('-done_at').values('done_at')[:1]
        Modulo.objects.filter(**{f'{prefix}_hecho': True}).update(**{
            f'{prefix}_completado_at': models.Subquery(latest),
        })


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_project_documents_crane_and_ferralla_rack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoCheckDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrabajadorOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='inferior_completado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='superior_completado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_montaje',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProyectoCheckEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.proyectocheckdefinicion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_estados', to='api.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'definicion'), name='unique_project_check')],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('EVENTO', 'Evento'), ('VACACIONES', 'Vacaciones')], default='EVENTO', max_length=16)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('notas', models.TextField(blank=True, max_length=4000)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='api.proyecto')),
                ('trabajadores', models.ManyToManyField(blank=True, related_name='eventos', to='api.trabajadoroficina')),
            ],
            options={
                'ordering': ['inicio', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gte', models.F('inicio'))), name='calendar_valid_dates')],
            },
        ),
        migrations.RunPython(backfill_phase_dates, migrations.RunPython.noop),
    ]
