# Generated by Django 5.2.10 on 2026-09-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_mesa_pending_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectocheckdefinicion',
            name='activo',
        ),
        migrations.CreateModel(
            name='ProyectoCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('origen', models.CharField(choices=[('PLANTILLA', 'Plantilla'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('completado', models.BooleanField(default=False)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api.proyecto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ProyectoCheckEstado',
        ),
        migrations.AddIndex(
            model_name='proyectocheck',
            index=models.Index(fields=['proyecto', 'completado'], name='api_proyect_proyect_caadff_idx'),
        ),
    ]
