# Generated by Django 5.2.10 on 2026-09-17 12:01

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_project_checklist_per_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoCheckAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to=api.models._check_attachment_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('subido_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['subido_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='proyectocheck',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectocheck',
            name='requiere_documento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyectocheck',
            name='requiere_fecha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyectocheckdefinicion',
            name='requiere_documento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyectocheckdefinicion',
            name='requiere_fecha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='proyectocheck',
            index=models.Index(fields=['fecha_limite'], name='api_proyect_fecha_l_72d33a_idx'),
        ),
        migrations.AddField(
            model_name='proyectocheckadjunto',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='api.proyectocheck'),
        ),
        migrations.AddField(
            model_name='proyectocheckadjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
