# Generated by Django 5.2.10 on 2026-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_checklist_dates_and_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectocheck',
            name='bloquea_produccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyectocheck',
            name='dias_antes_montaje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectocheck',
            name='requisitos',
            field=models.ManyToManyField(blank=True, related_name='dependientes', to='api.proyectocheck'),
        ),
        migrations.AddField(
            model_name='proyectocheckdefinicion',
            name='bloquea_produccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyectocheckdefinicion',
            name='dias_antes_montaje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectocheckdefinicion',
            name='requisitos',
            field=models.ManyToManyField(blank=True, related_name='dependientes', to='api.proyectocheckdefinicion'),
        ),
    ]
