# Generated by Django 5.2.10 on 2026-09-23 07:02

import django.db.models.deletion
from django.db import migrations, models


def enlazar_copias_existentes(apps, schema_editor):
    """Las copias sembradas antes del enlace se reconocen por titulo."""
    ProyectoCheck = apps.get_model('api', 'ProyectoCheck')
    ProyectoCheckDefinicion = apps.get_model('api', 'ProyectoCheckDefinicion')
    por_titulo = {}
    for definicion in ProyectoCheckDefinicion.objects.order_by('orden', 'id'):
        por_titulo.setdefault(definicion.titulo.strip().casefold(), definicion.id)
    for copia in ProyectoCheck.objects.filter(origen='PLANTILLA', definicion__isnull=True):
        definicion_id = por_titulo.get((copia.titulo or '').strip().casefold())
        if definicion_id is not None:
            copia.definicion_id = definicion_id
            copia.save(update_fields=['definicion'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_checklist_plazos_y_bloqueos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectocheck',
            name='definicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias', to='api.proyectocheckdefinicion'),
        ),
        migrations.RunPython(enlazar_copias_existentes, migrations.RunPython.noop),
    ]
