# Generated by Django 5.2.10 on 2026-09-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_checklist_enlace_definicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupobastidor',
            options={'ordering': ['proyecto', 'indice', 'sufijo']},
        ),
        migrations.RemoveConstraint(
            model_name='grupobastidor',
            name='unique_grupo_indice_per_proyecto',
        ),
        migrations.AddField(
            model_name='grupobastidor',
            name='dividido_de',
            field=models.ForeignKey(blank=True, help_text='Bastidor raiz del que esta parte es una division de fabricacion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='api.grupobastidor'),
        ),
        migrations.AddField(
            model_name='grupobastidor',
            name='sufijo',
            field=models.CharField(blank=True, default='', help_text='Letra de la division (B, C...). Vacio en el bastidor raiz.', max_length=2),
        ),
        migrations.AddField(
            model_name='mesaqueueitem',
            name='resume_image_index',
            field=models.PositiveIntegerField(blank=True, help_text='Imagen por la que iba esta fase cuando se aparto de la mesa; al volver a mostrarse continua desde ahi.', null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='orden_intra_previo',
            field=models.PositiveIntegerField(blank=True, help_text='Posicion que tenia en el bastidor raiz antes de dividirlo; se usa para recomponer el orden al unir. Null si no esta dividido.', null=True),
        ),
        migrations.AlterField(
            model_name='grupobastidor',
            name='indice',
            field=models.PositiveIntegerField(help_text='Numero de bastidor dentro del proyecto (1, 2, 3...). Las divisiones comparten el indice de su raiz.'),
        ),
        migrations.AddConstraint(
            model_name='grupobastidor',
            constraint=models.UniqueConstraint(fields=('proyecto', 'indice', 'sufijo'), name='unique_grupo_indice_per_proyecto'),
        ),
    ]
