# Generated by Django 5.2.10 on 2026-09-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_bastidores_divididos_y_reanudacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupobastidor',
            name='mesa_preferida',
            field=models.ForeignKey(blank=True, help_text='Mesa inferior a la que la ferralla ha llevado este bastidor. Null => lo reparte el planificador por carga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bastidores_fijados', to='api.mesa'),
        ),
    ]
