# Generated by Django 5.2.10 on 2026-09-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_bastidor_mesa_preferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupobastidor',
            name='en_espera',
            field=models.BooleanField(default=False, help_text='Apartado de las mesas (p.ej. sin acero cortado): ni el ni los modulos que le lleguen entran en cola hasta que se suelte.'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='modulos_previstos',
            field=models.PositiveIntegerField(blank=True, help_text='Total de modulos que tendra el proyecto aunque aun no esten todos subidos. Vacio => se usan los subidos. Sirve para el ritmo diario.', null=True),
        ),
    ]
