# Generated by Django 5.2.10 on 2026-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_modulos_previstos_y_bastidor_en_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='capture_horario',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
