# Generated by Django 5.2.10 on 2026-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_perfil_horario_por_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomesas',
            name='estrategia_cola_superior_previa',
            field=models.CharField(blank=True, default='', help_text='Estrategia automatica a la que volver al salir del orden manual.', max_length=20),
        ),
        migrations.AlterField(
            model_name='grupomesas',
            name='estrategia_cola_superior',
            field=models.CharField(choices=[('PLANIFICADA', 'Alternancia planificada'), ('ADAPTATIVA', 'Adaptar al avance real'), ('MANUAL', 'Orden manual')], default='PLANIFICADA', help_text='PLANIFICADA mantiene la alternancia teorica. ADAPTATIVA prioriza los superiores ya requeridos por las mesas inferiores. MANUAL respeta el orden que ponga la ferralla.', max_length=20),
        ),
    ]
