# Generated by Django 5.2.10 on 2026-09-29 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_cola_superior_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFabricacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fase', models.CharField(choices=[('INFERIOR', 'Inferior'), ('SUPERIOR', 'Superior')], max_length=20)),
                ('tipo', models.CharField(choices=[('INICIO', 'Empieza a mostrarse'), ('PASO', 'Cambio de imagen'), ('PAUSA', 'Se aparta de la mesa'), ('FIN', 'Marcado hecho')], max_length=10)),
                ('paso', models.PositiveIntegerField(blank=True, null=True)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.mesaqueueitem')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_fabricacion', to='api.mesa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_fabricacion', to='api.modulo')),
            ],
            options={
                'db_table': 'api_evento_fabricacion',
                'ordering': ['at', 'id'],
                'indexes': [models.Index(fields=['item', 'at'], name='evento_fab_item_at_idx')],
            },
        ),
    ]
