# Generated by Django 5.2.10 on 2026-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_eventos_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemodulofase',
            name='peso_malla_manual_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
