# Generated by Django 5.2.10 on 2026-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_malla_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='elementos_sueltos_archivo',
            field=models.FileField(blank=True, help_text='Excel con los elementos sueltos a llevar a obra (barras, vigas, zunchos) que no van dentro de un modulo.', null=True, upload_to='elementos_sueltos/'),
        ),
    ]
