# Generated by Django 5.2.10 on 2026-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_elementos_sueltos'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='url_monitor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
